-- SOLOVYEV STORE — full setup (paste into Supabase SQL Editor → Run)
-- After this: npm run seed:supabase

-- ── 001 initial ─────────────────────────────────────────────────────────────

create table if not exists products (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  category text not null check (category in ('sneakers', 'clothing', 'accessories')),
  price numeric not null default 0,
  original_price numeric,
  condition text not null default 'See description',
  brand text not null,
  badge text not null default 'hot',
  sizes jsonb not null default '[]'::jsonb,
  img text not null default '',
  status text not null default 'available' check (status in ('available', 'reserved', 'sold', 'new_drop', 'draft', 'made_to_order', 'brand_new')),
  sold boolean default false,
  description text,
  instagram_url text,
  instagram_shortcode text unique,
  source text default 'instagram',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_status_idx on products (status);
create index if not exists products_category_idx on products (category);
create index if not exists products_instagram_shortcode_idx on products (instagram_shortcode);

create table if not exists faq_items (
  id bigint generated by default as identity primary key,
  sort_order int not null default 0,
  question text not null,
  answer text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists store_config (
  id int primary key default 1 check (id = 1),
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  product_id bigint references products (id) on delete set null,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_type_idx on analytics_events (event_type);
create index if not exists analytics_events_created_idx on analytics_events (created_at desc);
create index if not exists analytics_events_product_idx on analytics_events (product_id);

create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists products_updated_at on products;
create trigger products_updated_at before update on products
  for each row execute function set_updated_at();

drop trigger if exists faq_items_updated_at on faq_items;
create trigger faq_items_updated_at before update on faq_items
  for each row execute function set_updated_at();

drop trigger if exists store_config_updated_at on store_config;
create trigger store_config_updated_at before update on store_config
  for each row execute function set_updated_at();

alter table products enable row level security;
alter table faq_items enable row level security;
alter table store_config enable row level security;
alter table analytics_events enable row level security;

drop policy if exists "Public read products" on products;
create policy "Public read products" on products
  for select
  using (status is distinct from 'draft');

drop policy if exists "Public read faq" on faq_items;
create policy "Public read faq" on faq_items for select using (true);

drop policy if exists "Public read config" on store_config;
create policy "Public read config" on store_config for select using (true);

drop policy if exists "Public insert analytics" on analytics_events;
create policy "Public insert analytics" on analytics_events for insert with check (true);

drop policy if exists "Public read analytics" on analytics_events;
create policy "Public read analytics" on analytics_events for select using (true);

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true),
       ('hero-images', 'hero-images', true)
on conflict (id) do nothing;

drop policy if exists "Public read product images" on storage.objects;
create policy "Public read product images" on storage.objects
  for select using (bucket_id = 'product-images');

drop policy if exists "Public read hero images" on storage.objects;
create policy "Public read hero images" on storage.objects
  for select using (bucket_id = 'hero-images');

-- ── 002 product images ────────────────────────────────────────────────────────

alter table products add column if not exists sort_order int not null default 0;

create table if not exists product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products (id) on delete cascade,
  image_url text not null,
  alt_text text,
  sort_order int not null default 0,
  object_position text not null default '50% 50%',
  created_at timestamptz not null default now()
);

create index if not exists product_images_product_id_idx on product_images (product_id, sort_order);

insert into product_images (product_id, image_url, sort_order, alt_text)
select id, img, 0, title
from products
where img is not null and img <> ''
  and not exists (
    select 1 from product_images pi where pi.product_id = products.id
  );

update products set sort_order = id where sort_order = 0;

alter table product_images enable row level security;

drop policy if exists "Public read product_images" on product_images;
create policy "Public read product_images" on product_images
  for select
  using (
    exists (
      select 1
      from products p
      where p.id = product_images.product_id
        and p.status is distinct from 'draft'
    )
  );
