-- SOLOVYEV STORE — full setup (paste into Supabase SQL Editor → Run)
-- After this: npm run seed:supabase

-- ── 001 initial ─────────────────────────────────────────────────────────────

create table if not exists products (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  category text not null check (category in ('sneakers', 'clothing', 'accessories')),
  price numeric not null default 0,
  original_price numeric,
  condition text not null default 'See description',
  brand text not null,
  badge text not null default 'hot',
  sizes jsonb not null default '[]'::jsonb,
  img text not null default '',
  status text not null default 'available' check (status in ('available', 'reserved', 'sold', 'new_drop', 'draft', 'made_to_order', 'brand_new')),
  sold boolean default false,
  description text,
  instagram_url text,
  instagram_shortcode text unique,
  source text default 'instagram',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_status_idx on products (status);
create index if not exists products_category_idx on products (category);
create index if not exists products_instagram_shortcode_idx on products (instagram_shortcode);

create table if not exists faq_items (
  id bigint generated by default as identity primary key,
  sort_order int not null default 0,
  question text not null,
  answer text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists store_config (
  id int primary key default 1 check (id = 1),
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  product_id bigint references products (id) on delete set null,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_type_idx on analytics_events (event_type);
create index if not exists analytics_events_created_idx on analytics_events (created_at desc);
create index if not exists analytics_events_product_idx on analytics_events (product_id);

create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists products_updated_at on products;
create trigger products_updated_at before update on products
  for each row execute function set_updated_at();

drop trigger if exists faq_items_updated_at on faq_items;
create trigger faq_items_updated_at before update on faq_items
  for each row execute function set_updated_at();

drop trigger if exists store_config_updated_at on store_config;
create trigger store_config_updated_at before update on store_config
  for each row execute function set_updated_at();

alter table products enable row level security;
alter table faq_items enable row level security;
alter table store_config enable row level security;
alter table analytics_events enable row level security;

drop policy if exists "Public read products" on products;
create policy "Public read products" on products
  for select
  using (status is distinct from 'draft');

drop policy if exists "Public read faq" on faq_items;
create policy "Public read faq" on faq_items for select using (true);

drop policy if exists "Public read config" on store_config;
create policy "Public read config" on store_config for select using (true);

drop policy if exists "Public insert analytics" on analytics_events;
drop policy if exists "Public read analytics" on analytics_events;
revoke all on analytics_events from public;
revoke all on analytics_events from anon;
revoke all on analytics_events from authenticated;

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true),
       ('hero-images', 'hero-images', true)
on conflict (id) do nothing;

drop policy if exists "Public read product images" on storage.objects;
create policy "Public read product images" on storage.objects
  for select using (bucket_id = 'product-images');

drop policy if exists "Public read hero images" on storage.objects;
create policy "Public read hero images" on storage.objects
  for select using (bucket_id = 'hero-images');

-- ── 002 product images ────────────────────────────────────────────────────────

alter table products add column if not exists sort_order int not null default 0;
alter table products add column if not exists clothing_type text;
alter table products drop constraint if exists products_clothing_type_check;
alter table products add constraint products_clothing_type_check check (
  clothing_type is null
  or clothing_type in ('pants', 'shorts', 'tshirts', 'sweaters', 'jackets')
);
create index if not exists products_clothing_type_idx on products (category, clothing_type);

create table if not exists product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products (id) on delete cascade,
  image_url text not null,
  alt_text text,
  sort_order int not null default 0,
  object_position text not null default '50% 50%',
  created_at timestamptz not null default now()
);

create index if not exists product_images_product_id_idx on product_images (product_id, sort_order);

insert into product_images (product_id, image_url, sort_order, alt_text)
select id, img, 0, title
from products
where img is not null and img <> ''
  and not exists (
    select 1 from product_images pi where pi.product_id = products.id
  );

update products set sort_order = id where sort_order = 0;

alter table product_images enable row level security;

drop policy if exists "Public read product_images" on product_images;
create policy "Public read product_images" on product_images
  for select
  using (
    exists (
      select 1
      from products p
      where p.id = product_images.product_id
        and p.status is distinct from 'draft'
    )
  );

-- ── 006 customer accounts ───────────────────────────────────────────────────

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  display_name text,
  phone text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references products(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

create table if not exists cart_items (
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references products(id) on delete cascade,
  size text not null default '',
  quantity int not null default 1 check (quantity between 1 and 99),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, product_id, size)
);

create table if not exists orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete restrict,
  order_ref text not null unique,
  status text not null default 'pending_whatsapp'
    check (status in (
      'pending_whatsapp',
      'in_chat',
      'paid',
      'shipped',
      'completed',
      'cancelled'
    )),
  currency_code text not null,
  currency_symbol text not null,
  subtotal numeric not null check (subtotal >= 0),
  whatsapp_url text,
  customer_phone text,
  admin_notes text,
  tracking_code text,
  shipping_method text,
  assignee text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references orders(id) on delete cascade,
  product_id bigint references products(id) on delete set null,
  product_title text not null,
  product_slug text not null,
  product_image text not null default '',
  size text not null default '',
  quantity int not null check (quantity between 1 and 99),
  unit_price numeric not null check (unit_price >= 0),
  created_at timestamptz not null default now()
);

create index if not exists favorites_user_idx on favorites(user_id, created_at desc);
create index if not exists cart_items_user_idx on cart_items(user_id, updated_at desc);
create index if not exists orders_user_idx on orders(user_id, created_at desc);
create index if not exists order_items_order_idx on order_items(order_id);

create or replace function create_customer_profile()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into profiles (id, email, display_name)
  values (new.id, coalesce(new.email, ''), nullif(new.raw_user_meta_data ->> 'display_name', ''))
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_customer_profile on auth.users;
create trigger on_auth_user_created_customer_profile
  after insert or update of email on auth.users
  for each row execute function create_customer_profile();
insert into profiles (id, email, display_name)
select id, coalesce(email, ''), nullif(raw_user_meta_data ->> 'display_name', '') from auth.users
on conflict (id) do update set email = excluded.email;

drop trigger if exists profiles_updated_at on profiles;
create trigger profiles_updated_at before update on profiles for each row execute function set_updated_at();
drop trigger if exists cart_items_updated_at on cart_items;
create trigger cart_items_updated_at before update on cart_items for each row execute function set_updated_at();
drop trigger if exists orders_updated_at on orders;
create trigger orders_updated_at before update on orders for each row execute function set_updated_at();

alter table profiles enable row level security;
alter table favorites enable row level security;
alter table cart_items enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;
revoke insert, update, delete on profiles from authenticated;
grant select on profiles to authenticated;
grant update (display_name, phone) on profiles to authenticated;
grant select, insert, update, delete on favorites to authenticated;
grant select, insert, update, delete on cart_items to authenticated;
revoke insert, update, delete on orders from authenticated;
revoke insert, update, delete on order_items from authenticated;
grant select on orders, order_items to authenticated;

drop policy if exists "Users read own profile" on profiles;
create policy "Users read own profile" on profiles for select using (auth.uid() = id);
drop policy if exists "Users update own profile" on profiles;
create policy "Users update own profile" on profiles for update using (auth.uid() = id) with check (auth.uid() = id);
drop policy if exists "Users manage own favorites" on favorites;
create policy "Users manage own favorites" on favorites for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users manage own cart" on cart_items;
create policy "Users manage own cart" on cart_items for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users read own orders" on orders;
create policy "Users read own orders" on orders for select using (auth.uid() = user_id);
drop policy if exists "Users create own orders" on orders;
create policy "Users create own orders" on orders for insert with check (auth.uid() = user_id);
drop policy if exists "Users read own order items" on order_items;
create policy "Users read own order items" on order_items for select
  using (exists (select 1 from orders where orders.id = order_items.order_id and orders.user_id = auth.uid()));
drop policy if exists "Users create own order items" on order_items;
create policy "Users create own order items" on order_items for insert
  with check (exists (select 1 from orders where orders.id = order_items.order_id and orders.user_id = auth.uid()));

create or replace function create_whatsapp_order(p_items jsonb, p_currency_code text, p_currency_symbol text)
returns table(order_id uuid, order_ref text, subtotal numeric)
language plpgsql security definer set search_path = public as $$
declare
  v_user_id uuid := auth.uid();
  v_order_id uuid := gen_random_uuid();
  v_order_ref text := 'SS-' || upper(substr(replace(v_order_id::text, '-', ''), 1, 10));
  v_subtotal numeric;
  v_item_count int;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) not between 1 and 50 then
    raise exception 'Invalid cart';
  end if;
  select count(*), sum(p.price * i.quantity) into v_item_count, v_subtotal
  from jsonb_to_recordset(p_items) as i(product_id bigint, size text, quantity int)
  join products p on p.id = i.product_id
  where i.quantity between 1 and 99 and p.status not in ('sold', 'reserved', 'draft');
  if v_item_count <> jsonb_array_length(p_items) or v_subtotal is null then
    raise exception 'Cart contains unavailable products';
  end if;
  insert into orders (id, user_id, order_ref, currency_code, currency_symbol, subtotal)
  values (v_order_id, v_user_id, v_order_ref, p_currency_code, p_currency_symbol, v_subtotal);
  insert into order_items (order_id, product_id, product_title, product_slug, product_image, size, quantity, unit_price)
  select v_order_id, p.id, p.title, p.slug, p.img, coalesce(i.size, ''), i.quantity, p.price
  from jsonb_to_recordset(p_items) as i(product_id bigint, size text, quantity int)
  join products p on p.id = i.product_id;
  return query select v_order_id, v_order_ref, v_subtotal;
end;
$$;
revoke all on function create_whatsapp_order(jsonb, text, text) from public;
grant execute on function create_whatsapp_order(jsonb, text, text) to authenticated;

-- ── 007 marketing consent ───────────────────────────────────────────────────

alter table profiles
  add column if not exists marketing_email_opt_in boolean not null default false;

alter table profiles
  add column if not exists marketing_email_opt_in_at timestamptz;

create table if not exists marketing_consent_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  granted boolean not null,
  privacy_version text not null,
  source text not null
    check (source in ('registration', 'account')),
  locale text,
  created_at timestamptz not null default now()
);

create index if not exists marketing_consent_events_user_idx
  on marketing_consent_events(user_id, created_at desc);

create index if not exists profiles_marketing_opt_in_idx
  on profiles(marketing_email_opt_in)
  where marketing_email_opt_in = true;

alter table marketing_consent_events enable row level security;

revoke all on marketing_consent_events from public;
revoke insert, update, delete on marketing_consent_events from authenticated;
grant select on marketing_consent_events to authenticated;

drop policy if exists "Users read own marketing consent events" on marketing_consent_events;
create policy "Users read own marketing consent events"
  on marketing_consent_events for select
  using (auth.uid() = user_id);

grant update (display_name, phone, marketing_email_opt_in, marketing_email_opt_in_at)
  on profiles to authenticated;

-- ── 008 CRM foundation ──────────────────────────────────────────────────────

alter table profiles
  add column if not exists tags text[] not null default '{}';

create table if not exists order_status_events (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references orders(id) on delete cascade,
  from_status text,
  to_status text not null,
  note text,
  created_by text,
  created_at timestamptz not null default now()
);

create index if not exists order_status_events_order_idx
  on order_status_events(order_id, created_at desc);

create table if not exists customer_notes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  body text not null,
  created_by text,
  created_at timestamptz not null default now()
);

create index if not exists customer_notes_user_idx
  on customer_notes(user_id, created_at desc);

create table if not exists inquiries (
  id uuid primary key default gen_random_uuid(),
  type text not null check (type in ('sell', 'trade', 'other')),
  name text not null default '',
  email text not null default '',
  phone text not null default '',
  message text not null default '',
  status text not null default 'new'
    check (status in ('new', 'in_progress', 'won', 'lost')),
  user_id uuid references auth.users(id) on delete set null,
  source text,
  admin_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists inquiries_status_idx
  on inquiries(status, created_at desc);

create index if not exists inquiries_email_idx
  on inquiries(email);

drop trigger if exists inquiries_updated_at on inquiries;
create trigger inquiries_updated_at before update on inquiries
  for each row execute function set_updated_at();

create table if not exists admin_tasks (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  due_at timestamptz,
  user_id uuid references auth.users(id) on delete set null,
  order_id uuid references orders(id) on delete set null,
  done boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists admin_tasks_due_idx
  on admin_tasks(done, due_at);

alter table order_status_events enable row level security;
alter table customer_notes enable row level security;
alter table inquiries enable row level security;
alter table admin_tasks enable row level security;

revoke all on order_status_events from public;
revoke insert, update, delete on order_status_events from authenticated;
grant select on order_status_events to authenticated;

revoke all on customer_notes from public;
revoke all on customer_notes from authenticated;

revoke all on inquiries from public;
revoke all on inquiries from authenticated;

revoke all on admin_tasks from public;
revoke all on admin_tasks from authenticated;

drop policy if exists "Users read own order status events" on order_status_events;
create policy "Users read own order status events"
  on order_status_events for select
  using (
    exists (
      select 1 from orders
      where orders.id = order_status_events.order_id
        and orders.user_id = auth.uid()
    )
  );

-- ── 009 order customer phone snapshot ───────────────────────────────────────

alter table orders add column if not exists customer_phone text;

-- ── 010 security hardening ──────────────────────────────────────────────────

revoke select on orders from authenticated;
grant select (
  id,
  user_id,
  order_ref,
  status,
  currency_code,
  currency_symbol,
  subtotal,
  whatsapp_url,
  customer_phone,
  tracking_code,
  shipping_method,
  created_at,
  updated_at
) on orders to authenticated;

revoke select on order_status_events from authenticated;
grant select (
  id,
  order_id,
  from_status,
  to_status,
  created_at
) on order_status_events to authenticated;

revoke select on profiles from authenticated;
grant select (
  id,
  email,
  display_name,
  phone,
  created_at,
  updated_at,
  marketing_email_opt_in,
  marketing_email_opt_in_at
) on profiles to authenticated;

revoke update on profiles from authenticated;
grant update (display_name, phone) on profiles to authenticated;

-- ── 011 clothing type ─────────────────────────────────────────────────────────

update products set clothing_type = null where category <> 'clothing';

update products
set clothing_type = 'jackets'
where category = 'clothing'
  and title ~* '\y(jacket|parka|shell)\y';

update products
set clothing_type = 'shorts'
where category = 'clothing'
  and clothing_type is null
  and title ~* '\yshorts\y';

update products
set clothing_type = 'sweaters'
where category = 'clothing'
  and clothing_type is null
  and title ~* '\y(hoodie|crewneck|sweatshirt|fleece|waffle)\y';

update products
set clothing_type = 'pants'
where category = 'clothing'
  and clothing_type is null
  and title ~* '\y(pants|jeans)\y';

update products
set clothing_type = 'tshirts'
where category = 'clothing'
  and clothing_type is null
  and (
    title ~* 't-?\s*shirt'
    or title ~* '\y(tee|polo|shirt|long\s*sleeve)\y'
  );


