-- SOLOVYEV STORE — initial schema

create table if not exists products (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  category text not null check (category in ('sneakers', 'clothing', 'accessories')),
  price numeric not null default 0,
  original_price numeric,
  condition text not null default 'See description',
  brand text not null,
  badge text not null default 'hot',
  sizes jsonb not null default '[]'::jsonb,
  img text not null default '',
  status text not null default 'available' check (status in ('available', 'reserved', 'sold', 'new_drop', 'draft')),
  sold boolean default false,
  description text,
  instagram_url text,
  instagram_shortcode text unique,
  source text default 'instagram',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_status_idx on products (status);
create index if not exists products_category_idx on products (category);
create index if not exists products_instagram_shortcode_idx on products (instagram_shortcode);

create table if not exists faq_items (
  id bigint generated by default as identity primary key,
  sort_order int not null default 0,
  question text not null,
  answer text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists store_config (
  id int primary key default 1 check (id = 1),
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  product_id bigint references products (id) on delete set null,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_type_idx on analytics_events (event_type);
create index if not exists analytics_events_created_idx on analytics_events (created_at desc);
create index if not exists analytics_events_product_idx on analytics_events (product_id);

-- updated_at trigger
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger products_updated_at before update on products
  for each row execute function set_updated_at();

create trigger faq_items_updated_at before update on faq_items
  for each row execute function set_updated_at();

create trigger store_config_updated_at before update on store_config
  for each row execute function set_updated_at();

-- RLS
alter table products enable row level security;
alter table faq_items enable row level security;
alter table store_config enable row level security;
alter table analytics_events enable row level security;

create policy "Public read products" on products for select using (true);
create policy "Public read faq" on faq_items for select using (true);
create policy "Public read config" on store_config for select using (true);
create policy "Public insert analytics" on analytics_events for insert with check (true);
create policy "Public read analytics" on analytics_events for select using (true);

-- Storage buckets (run via dashboard if SQL insert fails)
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true),
       ('hero-images', 'hero-images', true)
on conflict (id) do nothing;

create policy "Public read product images" on storage.objects
  for select using (bucket_id = 'product-images');

create policy "Public read hero images" on storage.objects
  for select using (bucket_id = 'hero-images');
