-- SOLOVYEV STORE — product images + sort order

alter table products add column if not exists sort_order int not null default 0;

create table if not exists product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products (id) on delete cascade,
  image_url text not null,
  alt_text text,
  sort_order int not null default 0,
  object_position text not null default '50% 50%',
  created_at timestamptz not null default now()
);

create index if not exists product_images_product_id_idx on product_images (product_id, sort_order);

-- Backfill existing single images
insert into product_images (product_id, image_url, sort_order, alt_text)
select id, img, 0, title
from products
where img is not null and img <> ''
  and not exists (
    select 1 from product_images pi where pi.product_id = products.id
  );

-- Set sort_order from id where still default
update products set sort_order = id where sort_order = 0;

alter table product_images enable row level security;

create policy "Public read product_images" on product_images for select using (true);

-- Storage bucket for optimized product images (run in Supabase dashboard if bucket exists)
-- insert into storage.buckets (id, name, public) values ('products', 'products', true)
-- on conflict do nothing;
