-- Customer accounts, saved commerce state, and WhatsApp order history

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  display_name text,
  phone text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references products(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

create table if not exists cart_items (
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references products(id) on delete cascade,
  size text not null default '',
  quantity int not null default 1 check (quantity between 1 and 99),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, product_id, size)
);

create table if not exists orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete restrict,
  order_ref text not null unique,
  status text not null default 'pending_whatsapp'
    check (status in ('pending_whatsapp', 'confirmed', 'cancelled', 'completed')),
  currency_code text not null,
  currency_symbol text not null,
  subtotal numeric not null check (subtotal >= 0),
  whatsapp_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references orders(id) on delete cascade,
  product_id bigint references products(id) on delete set null,
  product_title text not null,
  product_slug text not null,
  product_image text not null default '',
  size text not null default '',
  quantity int not null check (quantity between 1 and 99),
  unit_price numeric not null check (unit_price >= 0),
  created_at timestamptz not null default now()
);

create index if not exists favorites_user_idx on favorites(user_id, created_at desc);
create index if not exists cart_items_user_idx on cart_items(user_id, updated_at desc);
create index if not exists orders_user_idx on orders(user_id, created_at desc);
create index if not exists order_items_order_idx on order_items(order_id);

create or replace function create_customer_profile()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into profiles (id, email, display_name)
  values (
    new.id,
    coalesce(new.email, ''),
    nullif(new.raw_user_meta_data ->> 'display_name', '')
  )
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_customer_profile on auth.users;
create trigger on_auth_user_created_customer_profile
  after insert or update of email on auth.users
  for each row execute function create_customer_profile();

insert into profiles (id, email, display_name)
select id, coalesce(email, ''), nullif(raw_user_meta_data ->> 'display_name', '')
from auth.users
on conflict (id) do update set email = excluded.email;

drop trigger if exists profiles_updated_at on profiles;
create trigger profiles_updated_at before update on profiles
  for each row execute function set_updated_at();

drop trigger if exists cart_items_updated_at on cart_items;
create trigger cart_items_updated_at before update on cart_items
  for each row execute function set_updated_at();

drop trigger if exists orders_updated_at on orders;
create trigger orders_updated_at before update on orders
  for each row execute function set_updated_at();

alter table profiles enable row level security;
alter table favorites enable row level security;
alter table cart_items enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;

revoke insert, update, delete on profiles from authenticated;
grant select on profiles to authenticated;
grant update (display_name, phone) on profiles to authenticated;
grant select, insert, update, delete on favorites to authenticated;
grant select, insert, update, delete on cart_items to authenticated;
revoke insert, update, delete on orders from authenticated;
revoke insert, update, delete on order_items from authenticated;
grant select on orders, order_items to authenticated;

drop policy if exists "Users read own profile" on profiles;
create policy "Users read own profile" on profiles for select using (auth.uid() = id);
drop policy if exists "Users update own profile" on profiles;
create policy "Users update own profile" on profiles for update
  using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "Users manage own favorites" on favorites;
create policy "Users manage own favorites" on favorites for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users manage own cart" on cart_items;
create policy "Users manage own cart" on cart_items for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users read own orders" on orders;
create policy "Users read own orders" on orders for select using (auth.uid() = user_id);
drop policy if exists "Users create own orders" on orders;
create policy "Users create own orders" on orders for insert with check (auth.uid() = user_id);

drop policy if exists "Users read own order items" on order_items;
create policy "Users read own order items" on order_items for select
  using (exists (
    select 1 from orders where orders.id = order_items.order_id and orders.user_id = auth.uid()
  ));
drop policy if exists "Users create own order items" on order_items;
create policy "Users create own order items" on order_items for insert
  with check (exists (
    select 1 from orders where orders.id = order_items.order_id and orders.user_id = auth.uid()
  ));

create or replace function create_whatsapp_order(
  p_items jsonb,
  p_currency_code text,
  p_currency_symbol text
)
returns table(order_id uuid, order_ref text, subtotal numeric)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_order_id uuid := gen_random_uuid();
  v_order_ref text := 'SS-' || upper(substr(replace(v_order_id::text, '-', ''), 1, 10));
  v_subtotal numeric;
  v_item_count int;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) not between 1 and 50 then
    raise exception 'Invalid cart';
  end if;

  select count(*), sum(p.price * i.quantity)
  into v_item_count, v_subtotal
  from jsonb_to_recordset(p_items) as i(product_id bigint, size text, quantity int)
  join products p on p.id = i.product_id
  where i.quantity between 1 and 99
    and p.status not in ('sold', 'reserved', 'draft');

  if v_item_count <> jsonb_array_length(p_items) or v_subtotal is null then
    raise exception 'Cart contains unavailable products';
  end if;

  insert into orders (id, user_id, order_ref, currency_code, currency_symbol, subtotal)
  values (v_order_id, v_user_id, v_order_ref, p_currency_code, p_currency_symbol, v_subtotal);

  insert into order_items (
    order_id, product_id, product_title, product_slug, product_image, size, quantity, unit_price
  )
  select v_order_id, p.id, p.title, p.slug, p.img, coalesce(i.size, ''), i.quantity, p.price
  from jsonb_to_recordset(p_items) as i(product_id bigint, size text, quantity int)
  join products p on p.id = i.product_id;

  return query select v_order_id, v_order_ref, v_subtotal;
end;
$$;

revoke all on function create_whatsapp_order(jsonb, text, text) from public;
grant execute on function create_whatsapp_order(jsonb, text, text) to authenticated;
